### ISSUE TITLE
all pictures generated - x-axis titles are cut off slightly

### ISSUE THREAD

**Issue by BlackAndWhiteSoldier** [Joeoh/GitMyStats#90] opened 2016-03-28 21:00 UTC
sometimes it's just the first few letters in the word that comes up as an x-axis label, and sometimes it's not really a problem cause you know what it would mean anyway.
but the way that the crop cuts off the labels on the x-axis label for the punchcard makes it look completely wrong. 
If the time is a 2 digit number it cuts off the first digit, so that 10am looks like 0am, 12pm looks like 2pm and also you then can't tell the difference between 12pm and 2pm for example.

This would be fixed with cropping the image when it's created. I had a look myself but i've no idea how do do it.
This is also an issue with every other picture that's generated, but punchcard is the worst affected.

**Comment by BlackAndWhiteSoldier** [comment] 2016-03-28 21:02
![image](https://cloud.githubusercontent.com/assets/11335212/14090182/c659cad0-f530-11e5-8003-86e3c278a861.png)

**Comment by barischj** [comment] 2016-03-28 21:04
#70

**Comment by barischj** [comment] 2016-04-05 12:29
Gonna close this since it's just a duplicate of the longer existing #70

**Closed by barischj** 2016-04-05 12:29 UTC
Labels: bug, enhancement
